# Generated by Django 3.2.8 on 2021-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211022_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomodel',
            name='desc',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
