# Generated by Django 3.2.8 on 2021-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_geomodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomodel',
            name='radius',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
