# Generated by Django 3.2.8 on 2021-10-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_geomodel_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomodel',
            name='radius',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
