# Generated by Django 3.2.8 on 2021-11-12 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20211111_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomodel',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857),
        ),
    ]
