# Generated by Django 3.2.8 on 2021-11-15 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_geomodel_poly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomodel',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
